import { ProductStatus, VersionStatus } from "./types/enums";
import type { Image, Product } from "./types/types";

export const SampleData: Product[] = [
  {
    id: 1,
    externalId: "ext-1",
    storeId: 101,
    status: ProductStatus.Inactive,
    title: "MOON FRUIT Retinol Alternative Serum",
    handle: "moon-fruit-1-bakuchiol-peptides-retinol-alternative-serum",
    statistics: {
      views: 7923,
      // conversionRateLift: 34.2,
      // marginalRevenue: 100,
      // personalizedPercentage: 75,
      // addToCartRateLift: 50,
    },
    defaultVersionId: 130,
    versions: [
      {
        id: 101,
        productId: 1,
        versionTitle: "hydration",
        status: VersionStatus.Running,
        productTitle: "Product 1",
        heroImage:
          "https://cdn.thewirecutter.com/wp-content/media/2022/12/imacbuyingdesktop-2048px-0074-3x2-1.jpg?auto=webp&quality=75&width=1024",
        description:
          "<p>Description for Product 1 Version ADescription for Product 1 Version ADescription for Product 1 </p>",
        attributes: ["attr1attr1attr1attr1", "attr2", "attr2", "attr2", "attr2"],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 50,
          conversionRate: 1.5,
          marginalRevenue: 50,
          displayPercentage: 60,
          addToCartRate: 30,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
      {
        id: 102,
        productId: 1,
        versionTitle: "College Students",
        status: VersionStatus.Pending,
        productTitle: "Product 1",
        heroImage:
          "https://media.wired.com/photos/5fb2cc575c9914713ead03de/master/pass/Gear-Apple-MacBook-Air-top-down-SOURCE-Apple.jpg",
        description:
          "<p>Description for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version BDescription for Product 1 Version B</p>",
        attributes: ["College Stidemts", "attr4"],
        createdAt: new Date("2024-02-02"),
        statistics: {
          views: 60,
          conversionRate: 1.7,
          marginalRevenue: 60,
          displayPercentage: 70,
          addToCartRate: 35,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
      {
        id: 130,
        productId: 1,
        versionTitle: "Default Version",
        status: VersionStatus.Default,
        productTitle: "MOON FRUIT Retinol Alternative Serum",
        heroImage:
          "https://www.herbivorebotanicals.com/cdn/shop/files/MOON-FRUIT-SERUM-112090_V01.jpg?v=1703102622&width=1400",
        description:
          "<p>Revitalize your skin with Peptide and Bakuchiol, an advanced yet gentle retinol alternative. This blend boosts collagen, reducing wrinkles and lines while also hydrating the skin. Moon Fruit serum is non-comedogenic, so it won’t inflame pores and cause acne.</p>",
        attributes: [],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 7923,
          conversionRate: 1.4,
          marginalRevenue: 0,
          displayPercentage: 100,
          addToCartRate: 5.3,
          conversionRateLift: 0,
          addToCartRateLift: 0,
        },
      },
    ],
  },

  {
    id: 2,
    externalId: "ext-2",
    storeId: 101,
    status: ProductStatus.Active,
    title: "Product 2",
    handle: "Product 2".toLowerCase().replace(/ /g, "-"),
    statistics: {
      views: 200,
      conversionRateLift: 3.0,
      marginalRevenue: 120,
      personalizedPercentage: 80,
      addToCartRateLift: 60,
    },
    defaultVersionId: 131,
    versions: [
      {
        id: 103,
        productId: 2,
        versionTitle: "Version for product 2",
        status: VersionStatus.Running,
        productTitle: "Product 2",
        heroImage: "image-url-3",
        description: "<p>Description for Product 2 Default Version</p>",
        attributes: ["attr5", "attr6"],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 100,
          conversionRate: 2.0,
          marginalRevenue: 70,
          displayPercentage: 75,
          addToCartRate: 40,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
      {
        id: 131,
        productId: 2,
        versionTitle: "Default Version",
        status: VersionStatus.Default,
        productTitle: "Product 1",
        heroImage: "image-url-3",
        description: "<p>Default Product Description</p>",
        attributes: [],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 100,
          conversionRate: 2.0,
          marginalRevenue: 0,
          displayPercentage: 75,
          addToCartRate: 40,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
    ],
  },

  {
    id: 3,
    externalId: "ext-3",
    storeId: 103,
    status: ProductStatus.Inactive,
    title: "Product 3",
    handle: "Product 3".toLowerCase().replace(/ /g, "-"),
    statistics: {
      views: 150,
      // conversionRateLift: 2.5,
      // marginalRevenue: 100,
      // personalizedPercentage: 75,
      // addToCartRateLift: 50,
    },
    defaultVersionId: 132,
    versions: [
      {
        id: 132,
        productId: 3,
        versionTitle: "Default Version",
        status: VersionStatus.Default,
        productTitle: "Product 1",
        heroImage: "image-url-3",
        description: "<p>Default Product Description</p>",
        attributes: [],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 100,
          conversionRate: 2.0,
          marginalRevenue: 0,
          displayPercentage: 75,
          addToCartRate: 40,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
    ],
  },

  {
    id: 4,
    externalId: "ext-4",
    storeId: 104,
    status: ProductStatus.Active,
    title: "Product 4",
    handle: "Product 4".toLowerCase().replace(/ /g, "-"),
    statistics: {
      views: 250,
      conversionRateLift: 3.5,
      marginalRevenue: 140,
      personalizedPercentage: 85,
      addToCartRateLift: 65,
    },
    defaultVersionId: 134,
    versions: [
      {
        id: 104,
        productId: 4,
        versionTitle: "Version D",
        status: VersionStatus.Pending,
        productTitle: "Product 4",
        heroImage: "image-url-4",
        description: "<p>Description for Product 4 Version D</p>",
        attributes: ["attr7", "attr8"],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 125,
          conversionRate: 1.8,
          marginalRevenue: 75,
          displayPercentage: 80,
          addToCartRate: 45,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
      {
        id: 134,
        productId: 4,
        versionTitle: "Default Version",
        status: VersionStatus.Default,
        productTitle: "Product 1",
        heroImage: "image-url-3",
        description: "<p>Default Product Description</p>",
        attributes: [],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 100,
          conversionRate: 2.0,
          marginalRevenue: 0,
          displayPercentage: 75,
          addToCartRate: 40,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
    ],
  },
  {
    id: 5,
    externalId: "ext-5",
    storeId: 105,
    status: ProductStatus.Inactive,
    title: "Product 5",
    handle: "Product 5".toLowerCase().replace(/ /g, "-"),
    defaultVersionId: 135,
    statistics: {
      views: 300,
      conversionRateLift: 4.0,
      marginalRevenue: 160,
      personalizedPercentage: 90,
      addToCartRateLift: 70,
    },
    versions: [
      {
        id: 135,
        productId: 5,
        versionTitle: "Default Version",
        status: VersionStatus.Default,
        productTitle: "Product 1",
        heroImage: "image-url-3",
        description: "<p>Default Product Description</p>",
        attributes: [],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 100,
          conversionRate: 2.0,
          marginalRevenue: 0,
          displayPercentage: 75,
          addToCartRate: 40,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
    ],
  },
  {
    id: 6,
    externalId: "ext-6",
    storeId: 106,
    status: ProductStatus.Active,
    title: "Product 6",
    handle: "Product 6".toLowerCase().replace(/ /g, "-"),
    statistics: {
      views: 350,
      conversionRateLift: 4.5,
      marginalRevenue: 180,
      personalizedPercentage: 95,
      addToCartRateLift: 75,
    },
    defaultVersionId: 136,
    versions: [
      {
        id: 105,
        productId: 6,
        versionTitle: "Version E",
        status: VersionStatus.Rejected,
        productTitle: "Product 6",
        heroImage: "image-url-5",
        description: "<p>Description for Product 6 Version E</p>",
        attributes: ["attr9", "attr10"],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 175,
          conversionRate: 2.2,
          marginalRevenue: 90,
          displayPercentage: 85,
          addToCartRate: 50,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
      {
        id: 136,
        productId: 5,
        versionTitle: "Default Version",
        status: VersionStatus.Default,
        productTitle: "Product 1",
        heroImage: "image-url-3",
        description: "<p>Default Product Description</p>",
        attributes: [],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 100,
          conversionRate: 2.0,
          marginalRevenue: 0,
          displayPercentage: 75,
          addToCartRate: 40,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
    ],
  },
  {
    id: 7,
    externalId: "ext-7",
    storeId: 107,
    status: ProductStatus.Inactive,
    title: "Product 7",
    handle: "Product 7".toLowerCase().replace(/ /g, "-"),
    statistics: {
      views: 400,
    },
    defaultVersionId: 137,
    versions: [
      {
        id: 137,
        productId: 7,
        versionTitle: "Default Version",
        status: VersionStatus.Default,
        productTitle: "Product 1",
        heroImage: "image-url-3",
        description: "<p>Default Product Description</p>",
        attributes: [],
        createdAt: new Date("2024-02-05"),
        statistics: {
          views: 100,
          conversionRate: 2.0,
          marginalRevenue: 0,
          displayPercentage: 75,
          addToCartRate: 40,
          conversionRateLift: 2.5,
          addToCartRateLift: 1.5,
        },
      },
    ],
  },
];

export const DemoGeneratingVersionsArr = [
  {
    id: 1001,
    productId: 1,
    versionTitle: "",
    status: VersionStatus.Generating,
    productTitle: "",
    heroImage: "",
    description: "<p></p>",
    attributes: [],
    createdAt: new Date("2024-02-05"),
    statistics: {
      views: 0,
      conversionRate: 0,
      marginalRevenue: 0,
      displayPercentage: 0,
      addToCartRate: 0,
      conversionRateLift: 0,
      addToCartRateLift: 0,
    },
  },
  {
    id: 1002,
    productId: 1,
    versionTitle: "",
    status: VersionStatus.Generating,
    productTitle: "",
    heroImage: "",
    description: "<p></p>",
    attributes: [],
    createdAt: new Date("2024-02-05"),
    statistics: {
      views: 0,
      conversionRate: 0,
      marginalRevenue: 0,
      displayPercentage: 0,
      addToCartRate: 0,
      conversionRateLift: 0,
      addToCartRateLift: 0,
    },
  },
  {
    id: 1003,
    productId: 1,
    versionTitle: "",
    status: VersionStatus.Generating,
    productTitle: "",
    heroImage: "",
    description: "<p></p>",
    attributes: [],
    createdAt: new Date("2024-02-05"),
    statistics: {
      views: 0,
      conversionRate: 0,
      marginalRevenue: 0,
      displayPercentage: 0,
      addToCartRate: 0,
      conversionRateLift: 0,
      addToCartRateLift: 0,
    },
  },
];

export const DemoGeneratedVersions = [
  {
    id: 1001,
    productId: 3,
    versionTitle: "Version 1",
    status: VersionStatus.Pending,
    productTitle: "Title 1",
    heroImage: "image-url-1",
    description: "<p>description 1</p>",
    attributes: ["attr1", "attr2"],
    createdAt: new Date("2024-02-05"),
    statistics: {
      views: 0,
      conversionRate: 0,
      marginalRevenue: 0,
      displayPercentage: 0,
      addToCartRate: 0,
      conversionRateLift: 0,
      addToCartRateLift: 0,
    },
  },
  {
    id: 1002,
    productId: 3,
    versionTitle: "Version 2",
    status: VersionStatus.Pending,
    productTitle: "Title 2",
    heroImage: "image-url-2",
    description: "<p>description 2</p>",
    attributes: ["attr1", "attr2"],
    createdAt: new Date("2024-02-05"),
    statistics: {
      views: 0,
      conversionRate: 0,
      marginalRevenue: 0,
      displayPercentage: 0,
      addToCartRate: 0,
      conversionRateLift: 0,
      addToCartRateLift: 0,
    },
  },
  {
    id: 1003,
    productId: 3,
    versionTitle: "Version 3",
    status: VersionStatus.Pending,
    productTitle: "Title 3",
    heroImage: "image-url-3",
    description: "<p>description 3</p>",
    attributes: ["attr1", "attr2"],
    createdAt: new Date("2024-02-05"),
    statistics: {
      views: 0,
      conversionRate: 0,
      marginalRevenue: 0,
      displayPercentage: 0,
      addToCartRate: 0,
      conversionRateLift: 0,
      addToCartRateLift: 0,
    },
  },
];

export const sampleImages: Image[] = [
  {
    id: 1,
    url: "https://cdn.thewirecutter.com/wp-content/media/2022/12/imacbuyingdesktop-2048px-0074-3x2-1.jpg?auto=webp&quality=75&width=1024",
    product_id: 1, // assuming this image is for product 1
    alt: "Image 1 alt text",
    ai_description: "AI generated description for Image 1",
  },
  {
    id: 2,
    url: "https://media.wired.com/photos/5fb2cc575c9914713ead03de/master/pass/Gear-Apple-MacBook-Air-top-down-SOURCE-Apple.jpg",
    product_id: 2, // assuming this image is for product 2
    alt: "Image 2 alt text",
    ai_description: "AI generated description for Image 2",
  },
  {
    id: 3,
    url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kingston.com%2Fen%2Fblog%2Fpc-performance%2Ftips-to-speed-up-mac&psig=AOvVaw3RQvcVyj0awLdYK-kHZJPU&ust=1706911298466000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCMCCqJ-Si4QDFQAAAAAdAAAAABAj",
    product_id: 3, // assuming this image is for product 3
    alt: "Image 3 alt text",
    ai_description: "AI generated description for Image 3",
  },
  {
    id: 4,
    url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fmac&psig=AOvVaw3RQvcVyj0awLdYK-kHZJPU&ust=1706911298466000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCMCCqJ-Si4QDFQAAAAAdAAAAABAs",
    product_id: 4, // assuming this image is for product 4
    alt: "Image 4 alt text",
    ai_description: "AI generated description for Image 4",
  },
  {
    id: 5,
    url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.intego.com%2Fmac-security-blog%2Fhow-to-set-up-your-own-mac-server-with-an-old-or-new-mac%2F&psig=AOvVaw3RQvcVyj0awLdYK-kHZJPU&ust=1706911298466000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCMCCqJ-Si4QDFQAAAAAdAAAAABAa",
    product_id: 5, // assuming this image is for product 5
    alt: "Image 5 alt text",
    ai_description: "AI generated description for Image 5",
  },
];

export default SampleData;
